import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'Keerti_Sharma',
      email: 'admin@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('1234', 8),
      isAdmin: false,
    },
  ],

  products: [
    {
      "sr_no": "1",
      name: 'Nike Slim Shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 400,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      "sr_no": "2",
      name: 'Adidas Fit Shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 600,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      "sr_no": "3",
      name: 'Lacoste Free Shirt',
      category: 'Shirts',
      image: '/images/p3.jpg',
      price: 630,
      countInStock: 0,
      brand: 'Lacoste',
      rating: 4.8,
      numReviews: 17,
      description: 'high quality product',
    },
    {
      "sr_no": "4",
      name: 'Nike Slim Pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 499,
      countInStock: 15,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
    {
      "sr_no": "5",
      name: 'Puma Slim Pant',
      category: 'Pants',
      image: '/images/p5.jpg',
      price: 449,
      countInStock: 5,
      brand: 'Puma',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      "sr_no": "6",
      name: 'Adidas Fit Pant',
      category: 'Pants',
      image: '/images/p6.jpg',
      price: 699,
      countInStock: 12,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 15,
      description: 'high quality product',
    },
    {
      "sr_no": "7",
      "name": "Babyhug Half Sleeves Tee Dino Print - Yellow",
      "category": "Boys T-Shirt",
      "image": "/images/Kids/boysproduct/tshirt-1.webp",
      "price": 200,
      "countInStock": 5,
      "brand": "Babyhug",
      "rating": 4.3,
      "numReviews": 20,
      "description": "high Quality Product"
    },
    {
      "sr_no": "8",
      "name": "Babyhug Half Sleeves  Boat Print - White Blue",
      "category": "Boys T-Shirt",
      "image": "/images/Kids/boysproduct/tshirt-2.webp",
      "price": 250,
      "countInStock": 10,
      "brand": "Babyhug",
      "rating": 4.6,
      "numReviews": 19,
      "description": "high Quality Product"
    },
    {
      "sr_no": "9",
      "name": "Babyhug Half Sleeves - Yellow Navy Blue",
      "category": "Boys T-Shirt",
      "image": "/images/Kids/boysproduct/tshirt-3.webp",
      "price": 300,
      "countInStock": 8,
      "brand": "Babyhug",
      "rating": 4.5,
      "numReviews": 49,
      "description": "high Quality Product"
    },
    {
      "sr_no": "10",
      "name": "Pine Kids Captain America Print - Blue",
      "category": "Boys T-Shirt",
      "image": "/images/Kids/boysproduct/tshirt-4.webp",
      "price": 315,
      "countInStock": 6,
      "brand": "Pine Kids",
      "rating": 4.6,
      "numReviews": 30,
      "description": "high Quality Product"
    },
    {
      "sr_no": "11",
      "name": "Kookie Kids Full Sleeves Tshirts Blue 130 Boy        ",
      "category": "Boys TShirt",
      "image": "/images/Kids/boysproduct/tshirt-5.webp",
      "price": 450,
      "countInStock": 12,
      "brand": "Kookie",
      "rating": 4.5,
      "numReviews": 32,
      "description": "high Quality Product"
    },
    {
      "sr_no": "12",
      "name": "Ollypop Half Sleeves T-Shirt Robot Print - Black",
      "category": "Boys T-Shirt",
      "image": "/images/Kids/boysproduct/tshirt-6.webp",
      "price": 280,
      "countInStock": 12,
      "brand": "Ollypop",
      "rating": 4.8,
      "numReviews": 38,
      "description": "high Quality Product"
    },
    {
      "sr_no": "13",
      "name": "Boys Printed Cotton Blend T Shirt White",
      "category": "Boys T-Shirt",
      "image": "/images/Kids/boysproduct/tshirt-7.jpeg",
      "price": 380,
      "countInStock": 12,
      "brand": "Ollypop",
      "rating": 4.8,
      "numReviews": 38,
      "description": "high Quality Product"
    },
    {
      "sr_no": "14",
      "name": "Crayonflakes Half Sleeves Tshirt - Red",
      "category": "Boys T-Shirt",
      "image": "/images/Kids/boysproduct/tshirt-8.webp",
      "price": 380,
      "countInStock": 12,
      "brand": "Crayonflakes",
      "rating": 4.8,
      "numReviews": 38,
      "description": "high Quality Product"
    },
    {
      "sr_no": "15",
      "name": "Marvel Spiderman Tshirt For Kids",
      "category": "Boys T-Shirt",
      "image": "/images/Kids/boysproduct/tshirt-9.jpg",
      "price": 599,
      "countInStock": 15,
      "brand": "Marvel",
      "rating": 4.2,
      "numReviews": 58,
      "description": "high Quality Product"
    },
    {
      "sr_no": "16",
      "name": "Boys Printed Cotton Blend T Shirt Yellow",
      "category": "Boys T-Shirt",
      "image": "/images/Kids/boysproduct/tshirt-10.jpeg",
      "price": 615,
      "countInStock": 12,
      "brand": "Ollypop",
      "rating": 4.8,
      "numReviews": 38,
      "description": "high Quality Product"
    },
    {
      "sr_no": "17",
      "name": "Regular fit formal shirt",
      "category": "formal wear",
      "image": "/images/men/menproduct/formal-wear/regular-fit-formal-shirt-1.webp",
      "price": 519,
      "countInStock": 5,
      "brand": "Jainish",
      "rating": 4.5,
      "numReviews": 100,
      "description": "high Quality Product"
    },
    {
      "sr_no": "18",
      "name": "Slim fit formal shirt",
      "category": "formal wear",
      "image": "/images/men/menproduct/formal-wear/slim-fit-formal-shirt-2.webp",
      "price": 1000,
      "countInStock": 10,
      "brand": "BlackBerries",
      "rating": 3.9,
      "numReviews": 120,
      "description": "high Quality Product"
    },
    {
      "sr_no": "19",
      "name": "Slim fit formal shirt",
      "category": "formal wear",
      "image": "/images/men/menproduct/formal-wear/formal-shirt-3.webp",
      "price": 719,
      "countInStock": 34,
      "brand": "Hancock",
      "rating": 3.5,
      "numReviews": 100,
      "description": "high Quality Product"
    },
    {
      "sr_no": "20",
      "name": "Slim breasted blazer",
      "category": "formal wear",
      "image": "/images/men/menproduct/formal-wear/blazer-4.webp",
      "price": 3000,
      "countInStock": 10,
      "brand": "Louis Phillipine",
      "rating": 4.5,
      "numReviews": 800,
      "description": "high Quality Product"
    },
    {
      "sr_no": "21",
      "name": "slim fit formal trousers",
      "category": "formal wear",
      "image": "/images/men/menproduct/formal-wear/formal-trouser-5.webp",
      "price": 700,
      "countInStock": 15,
      "brand": "Hancock",
      "rating": 3.7,
      "numReviews": 50,
      "description": "high Quality Product"
    },
    {
      "sr_no": "22",
      "name": "slim fit formal shirt",
      "category": "formal wear",
      "image": "/images/men/menproduct/formal-wear/formal-shirt-6.webp",
      "price": 500,
      "countInStock": 10,
      "brand": "Jainish",
      "rating": 3.2,
      "numReviews": 120,
      "description": "high Quality Product"
    },
    {
      "sr_no": "23",
      "name": "Single-breasted Suit",
      "category": "formal wear",
      "image": "/images/men/menproduct/formal-wear/formal-suit-7.webp",
      "price": 4500,
      "countInStock": 10,
      "brand": "Park Avenue",
      "rating": 4.7,
      "numReviews": 80,
      "description": "high Quality Product"
    },
    {
      "sr_no": "24",
      "name": "Slim fit formal Trousers",
      "category": "formal wear",
      "image": "/images/men/menproduct/formal-wear/formal-trousers-8.webp",
      "price": 740,
      "countInStock": 50,
      "brand": "Louis Phillipi",
      "rating": 3.9,
      "numReviews": 120,
      "description": "high Quality Product"
    }
    ,
    {
      "sr_no": "25",
      "name": "Women pants",
      "category": "pants",
      "image": "/images/women/women-product1.jpg",
      "price": 400,
      "countInStock": 5,
      "brand": "Puma",
      "rating": 4.5,
      "numReviews": 10,
      "description": "high Quality Product"
    },
    {
      "sr_no": "26",
      "name": "ethnic wear anarkali",
      "category": "anarkali suits",
      "image": "/images/women/ethnic-wear-product1.jpg",
      "price": 1000,
      "countInStock": 10,
      "brand": "Puma",
      "rating": 4,
      "numReviews": 12,
      "description": "high Quality Product"
    },
    {
      "sr_no": "27",
      "name": "Ethnic Anarkali",
      "category": "Anarkali suits",
      "image": "/images/women/ethnic-wear-product2.jpg",
      "price": 1400,
      "countInStock": 8,
      "brand": "Puma",
      "rating": 4.2,
      "numReviews": 19,
      "description": "high Quality Product"
    },
    {
      "sr_no": "28",
      "name": "ethnic wear anarkali",
      "category": "Anarkali suit",
      "image": "/images/women/ethnic-wear-product3.jpg",
      "price": 800,
      "countInStock": 6,
      "brand": "Puma",
      "rating": 4.6,
      "numReviews": 20,
      "description": "high Quality Product"
    },
    {
      "sr_no": "29",
      "name": "Anarkali",
      "category": "Anarkali suits",
      "image": "/images/women/indo-western-wear-product1.jpg",
      "price": 1400,
      "countInStock": 12,
      "brand": "Puma",
      "rating": 4.5,
      "numReviews": 10,
      "description": "high Quality Product"
    },
    {
      "sr_no": "30",
      "name": "indo-western saree",
      "category": "saree",
      "image": "/images/women/indo-western-wear-product2.jpg",
      "price": 800,
      "countInStock": 7,
      "brand": "Puma",
      "rating": 4.5,
      "numReviews": 16,
      "description": "high Quality Product"
    },
    {
      "sr_no": "31",
      "name": "indo-western crop-top",
      "category": "crop-top",
      "image": "/images/women/indo-western-wear-product3.jpg",
      "price": 500,
      "countInStock": 5,
      "brand": "Puma",
      "rating": 3,
      "numReviews": 25,
      "description": "high Quality Product"
    },
    {
      "sr_no": "32",
      "name": "Middy",
      "category": "Middy",
      "image": "/images/women/indo-western-wear-product4.jpg",
      "price": 600,
      "countInStock": 0,
      "brand": "Puma",
      "rating": 4.3,
      "numReviews": 30,
      "description": "high Quality Product"
    },
    {
      "sr_no": "33",
      "name": "A-Line kurta",
      "category": "Kurta",
      "image": "/images/Women/womenproduct/Kurta/kurta-1.webp",
      "price": 600,
      "countInStock": 5,
      "brand": "Ahika",
      "rating": 4.1,
      "numReviews": 30,
      "description": "high Quality Product"
    },
    { 
      "sr_no": "34",
      "name": "Straight kurta",
      "category": "Kurta",
      "image": "/images/Women/womenproduct/Kurta/kurta-2.webp",
      "price": 550,
      "countInStock": 5,
      "brand": "Ahika",
      "rating": 4.1,
      "numReviews": 39,
      "description": "high Quality Product"
    },
    { 
      "sr_no": "35",
      "name": "Maxi dress",
      "category": "Party-wear Dress",
      "image": "/images/Women/womenproduct/party-dresses/maxi-dress-2.webp",
      "price": 950,
      "countInStock": 4,
      "brand": "Ahika",
      "rating": 4.6,
      "numReviews": 390,
      "description": "Party wear Product"
    },
    {
      "sr_no": "36",
      "name": "Net Maxi dress",
      "category": "Party-wear Dress",
      "image": "/images/Women/womenproduct/party-dresses/net-maxi-dress-3.webp",
      "price": 1050,
      "countInStock": 14,
      "brand": "Ahika",
      "rating": 4.0,
      "numReviews": 300,
      "description": "Party wear Product"
    },
    { 
      "sr_no": "37",
      "name": "Sheath dress",
      "category": "Party-wear Dress",
      "image": "/images/Women/womenproduct/party-dresses/sheath-dress-1.webp",
      "price": 700,
      "countInStock": 10,
      "brand": "Ahika",
      "rating": 4.1,
      "numReviews": 370,
      "description": "Party wear Product"
    },
  ],
};

export default data;